# Generated by Django 5.1 on 2025-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_message_session_analysissession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='user',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='browser_session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AnalysisHistory',
        ),
    ]
