# Generated by Django 5.1 on 2025-07-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_remove_analysissession_file_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissession",
            name="analysis_type",
        ),
        migrations.RemoveField(
            model_name="analysissession",
            name="browser_session_key",
        ),
        migrations.RemoveField(
            model_name="analysissession",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="analysissession",
            name="status",
        ),
    ]
