# Generated by Django 5.1 on 2025-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_graph_html', models.TextField(blank=True, null=True)),
                ('hour_graph_html', models.TextField(blank=True, null=True)),
                ('score_graph_html', models.TextField(blank=True, null=True)),
                ('user_col', models.CharField(blank=True, max_length=100, null=True)),
                ('time_col', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '분석 세션',
                'verbose_name_plural': '분석 세션들',
                'ordering': ['-created_at'],
            },
        ),
    ]
