# Generated by Django 5.1 on 2025-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='user_graph_html',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='hour_graph_html',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='score_graph_html',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='user_col',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='time_col',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
