# Generated by Django 5.1 on 2025-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_anomalylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissession",
            name="hour_graph_html",
        ),
        migrations.AddField(
            model_name="analysissession",
            name="hour_graph_html_top10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="hour_graph_html_top3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="threshold",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
