# Generated by Django 5.1 on 2025-07-24 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_anomalylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalylog",
            name="anomaly_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="anomalylog",
            name="session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="anomalylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["user", "-created_at"], name="web_anomaly_user_id_1b19db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["session_id", "user"], name="web_anomaly_session_e85885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalylog",
            index=models.Index(
                fields=["-anomaly_count", "user"], name="web_anomaly_anomaly_a2ba1d_idx"
            ),
        ),
    ]
