# Generated by Django 5.1 on 2025-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_anomalylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysissession',
            old_name='hour_graph_html',
            new_name='hour_graph_html_top10',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='hour_graph_html_top3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
