# Generated by Django 5.1 on 2025-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_anomalylog_anomaly_count_anomalylog_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="anomalylog",
            name="web_anomaly_user_id_1b19db_idx",
        ),
        migrations.RemoveIndex(
            model_name="anomalylog",
            name="web_anomaly_session_e85885_idx",
        ),
        migrations.RemoveIndex(
            model_name="anomalylog",
            name="web_anomaly_anomaly_a2ba1d_idx",
        ),
        migrations.RemoveField(
            model_name="anomalylog",
            name="anomaly_count",
        ),
        migrations.RemoveField(
            model_name="anomalylog",
            name="session_id",
        ),
        migrations.AlterField(
            model_name="anomalylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
