# Generated by Django 5.1 on 2025-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_remove_analysissession_hour_graph_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="threshold_mode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
